name = "zackbissell-brand-hub"
compatibility_date = "2024-07-01"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# Build configuration  
[build]
command = "npm install --legacy-peer-deps && npm run build"
