name = "zackbissell-brand-hub"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

# Static site configuration
[assets.not_found_handling]
mode = "single-page-application"

# R2 bucket binding for additional assets
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "main"

# Build configuration
[build]
command = "npm install --legacy-peer-deps && npm run build"
