name: bmad-creator-tools
version: 1.9.0
short-title: Tools for creating BMad framework components
description: Tools for creating and extending BMad framework components.
author: Brian (BMad)
slashPrefix: bmadCreator
