name: bmad-2d-unity-game-dev
version: 1.1.1
short-title: 2D game development with Unity & C#
description: >-
  2D Game Development expansion pack for BMad Method - Unity & C#
  focused
author: pbean (PinkyD)
slashPrefix: bmad2du